export default Object.freeze({
  INSERTED_SUCCESSFULLY: 'Data inserted successfully',
  SUCCESSFULLY_FETCHED: 'fetched data Successfully',
  DELETE_SUCCESSFUL: 'Deleted successfully',
  DATA_UPDATED: 'Data updated successfully',
  FOUND: 'Found data successFully',
  USER_CREATED: 'User created successfully',
  TOKEN_GENERATED: 'Token generated successfully',
  LOGGED_IN: 'Logged in successfully',
  NO_TOKEN: 'No Token provided',
  TOKEN_FAIL: 'Token authentication failed.',
  NO_REQUEST_BODY: 'No request body',
  DUPLICATE_ENTRIES: 'Duplicate entries has been found',
  DUPLICATE_RECORD: 'Duplicate record has been found',
  NO_RECORD_FOUND: 'No record found',
  INVALID_CREDENTIALS: 'Please check the credentials',
  INVALID_INPUT: 'Invalid,please provide a Valid input',
  CANNOT_FETCH: 'Cannot fetch Data',
  NOT_INSERTED: 'Data not inserted properly',
  UPDATE_FAIL: 'failed to update data',
  USER_NOT_CREATED: 'User creation unsuccessful',
  PASS_INCORRECT: 'password is incorrect,please provide a valid password',
  NO_COOKIE: 'Cookies not found',
  TOKEN_GEN_FAIL: 'Token generation failed',
  DATA_NOT_SAVED: 'Data not saved',
  EMAIL_NOT_EXIST: 'Email does not exist',
  PASSWORD_UPDATE: 'Password Updated successfully',
  PASSWORD_NOT_UPDATE: 'Failed to update password',
  INVALID_TOKEN: 'Invalid token',
  INVALID_DATE: 'Please provide a Valid Date',
  USER_NOT_AUTHORIZED: 'User is Not Authorized ,Please contact admin',
});
